config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "site#index"

  match '/dashboard' => 'dashboard#index', :via => [:get]
  match '/ranking' => 'dashboard#ranking', :via => [:get]
  match '/wins' => 'dashboard#wins', :via => [:get]

  resources :tasks do
    post :share, :on => :member
  end

  resources :posts do
    post :like, :on => :member
    post :unlike, :on => :member
  end

  resources :comments, only: [:index, :create]
  
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  match '/actions/:task_id/participate' => 'actions#participate', :via => [:post]
  match '/actions/:action_id/confirmate' => 'actions#confirmate', :via => [:post]
  match '/actions/:action_id/finalize' => 'actions#finalize', :via => [:post]

end

app/views/panel/shared/_avatar.html.erb
<%
  if user_name.blank?
    avatar = "??"
  else
    avatarArray = user_name.split

    if avatarArray.size > 1
      avatar = avatarArray[0][0].upcase + avatarArray[avatarArray.size - 1][0].upcase
    else
      avatar = avatarArray[0][0].upcase + avatarArray[0][1].upcase
    end
  end
%>

<div class="avatar-name avatar-sm">
  <p >
    <%= avatar %>
  </p>
</div>
<div class="player">
  <p>
    <%= user_name.blank? ? "??" : user_name %>
  </p>
</div>

app/views/panel/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="badges">
      <ul>
        <li>
          <p> Total de medalhas </p>
        </li>
        <li>
          <div class="badges-user">
            <p><%= current_user.badges.count %></p>
          </div>
        </li>
      </ul>
    </div>

    <div class="level">
      <ul>
        <li>
          <p> Nível </p>
        </li>
        <li>
          <div class="level-user">
            <p><%= current_user.level %></p>
          </div>
        </li>
      </ul>
    </div>

    <div class="points">
      <ul>
        <li>
          <p> Total de pontos </p>
        </li>
        <li>
          <div class="points-user">
            <p><%= current_user.points %></p>
          </div>
        </li>
      </ul>
    </div>

    <%
      @points = current_user.points
      percent = 0
      calc = 250
    %>

    <% if @points > 1 && @points < 250 %>
      <% percent = (@points * 100) / 250 %>
      <% calc = 250 - @points %>
    <% elsif @points >= 250 && @points < 500 %>
      <% percent = (@points * 100) / 500 %>
      <% calc = 500 - @points %>
    <% elsif @points >= 500 && @points < 1000 %>
      <% percent = (@points * 100) / 1000 %>
      <% calc = 1000 - @points %>
    <% elsif @points >= 1000 %>
      <% percent = 100 %>
      <% calc = 0 %>
    <% end %>

    <div class="progress-level">
      <span class="green" style="width: <%= percent %>%;"><span><%= calc %> pontos</span></span>
    </div>
  </div>
</footer>

app/views/panel/shared/_header.html.erb
<%
  if current_user.name.blank?
    avatar = "??"
  else
    avatarArray = current_user.name.split

    if avatarArray.size > 1
      avatar = avatarArray[0][0].upcase + avatarArray[avatarArray.size - 1][0].upcase
    else
      avatar = avatarArray[0][0].upcase + avatarArray[0][1].upcase
    end
  end
%>

<header>
  <div class="row">
    <div class="menu-left">
      <ul>
        <li>
          <div class="avatar avatar-name avatar-lg">
            <p >
              <%= avatar %>
            </p>
          </div>
        </li>
        <li class="menu">
          <%= link_to 'Início', dashboard_path(), class: "#{'active' if @menu_context == :dashboard}" %>
        </li>
        <li class="menu">
          <%= link_to 'Timeline', posts_path(), class: "#{'active' if @menu_context == :timeline}" %>
        </li>
        <li class="menu">
          <%= link_to "Ações", tasks_path(), class: "#{'active' if @menu_context == :tasks}" %>
        </li>
      </ul>
    </div>
    <div class="menu-right">
      <!--  Sugestão Lucas: Usar SVG https://css-tricks.com/icon-fonts-vs-svg/-->
      <ul>
        <li>
          <%= link_to "Minha conta", edit_user_registration_path() %>
        </li>
        <li>
          <%= link_to(destroy_user_session_path, { method: 'delete' }) do %>
            <i class="fa fa-sign-out"></i> Sair
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>