config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "site#index"

  match '/dashboard' => 'dashboard#index', :via => [:get]
  match '/ranking' => 'dashboard#ranking', :via => [:get]
  match '/wins' => 'dashboard#wins', :via => [:get]

  resources :tasks do
    post :share, :on => :member
  end

  resources :posts do
    post :like, :on => :member
    post :unlike, :on => :member
  end

  resources :comments, only: [:index, :create]
  
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  match '/actions/:task_id/participate' => 'actions#participate', :via => [:post]
  match '/actions/:action_id/confirmate' => 'actions#confirmate', :via => [:post]
  match '/actions/:action_id/finalize' => 'actions#finalize', :via => [:post]

end

app/controllers/dashboard_controller.rb
class DashboardController < InheritedResources::Base

  before_action :authenticate_user!
  before_action :check_rank_rules
  before_action :set_menu_context, if: ->() { user_signed_in? }

  def set_menu_context
    @menu_context = actual_menu_context
  end

  def index
  end

  def ranking
  end

  def wins
  end

  def check_rank_rules
    Merit::RankRules.new.check_rank_rules
  end

  private

  def actual_menu_context
    :dashboard
  end

end

app/views/dashboard/_actions_pending.html.erb
<div class="box">
  <div class="title">
    <h1><i class="fa fa-heart"></i> Ações pendentes</h1>
  </div>

  <div class="row box-table table-header">
    <div class="col-sm-2">
      <p>Situação</p>
    </div>
    <div class="col-sm-3">
      <p>Ação</p>
    </div>
    <div class="col-sm-3">
    </div>
    <div class="col-sm-2">
      <p>Expira em</p>
    </div>
    <div class="col-sm-2">
    </div>
  </div>

  <% current_user.actions.where(status: 0).each do |action| %>
    <div class="row box-table">
      <div class="col-sm-2">
        <p><span class="lg-status status-pending">Pendente</span></p>
      </div>
      <div class="col-sm-3">
        <p><%= action.task.title %></p>
      </div>
      <div class="col-sm-3">
        <p><%= link_to 'Ver detalhes', task_path(action.task), class: "btn-sm btn-info" %></p>
      </div>
      <div class="col-sm-2">
        <p><%= distance_of_time_in_words(Date.today, action.task.try(:expires_on)) %></p>
      </div>
      <div class="col-sm-2">
        <%= link_to 'Finalizar', '#', class: "btn-sm btn-create cta-confirmate", :"data-action-id" => "#{action.id}" %>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/_actions_requiring_approval.html.erb
<div class="box">
  <div class="title">
    <h1><i class="fa fa-heart"></i> Ações para aprovar</h1>
  </div>

  <div class="row box-table table-header">
    <div class="col-sm-3">
      <p>Realizada por</p>
    </div>
    <div class="col-sm-2">
      <p>Ação</p>
    </div>
    <div class="col-sm-3">
    </div>
    <div class="col-sm-2">
      <p>Expira em</p>
    </div>
    <div class="col-sm-2">
    </div>
  </div>

  <% Action.actions_requiring_approval(current_user.tasks.select(:id)).each do |action| %>
    <div class="row box-table">
      <div class="col-sm-3">
        <p>
          <%= render 'panel/shared/avatar', user_name: action.user.name %>        
        </p>
      </div>
      <div class="col-sm-2">
        <p><%= action.task.try(:title) %></p>
      </div>
      <div class="col-sm-3">
        <p><%= link_to 'Ver detalhes', task_path(action.task), class: "btn-sm btn-info" %></p>
      </div>
      <div class="col-sm-2">
        <p><%= distance_of_time_in_words(Date.today, action.task.try(:expires_on)) %></p>
      </div>
      <div class="col-sm-2">
        <p><%= link_to 'Aprovar', '#', class: "btn-sm btn-create cta-finalize", :"data-action-id" => "#{action.id}" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/_actions_waiting.html.erb
<div class="box">
  <div class="title">
    <h1><i class="fa fa-heart"></i> Ações finalizadas</h1>
  </div>

  <div class="row box-table table-header">
    <div class="col-sm-2">
      <p>Situação</p>
    </div>
    <div class="col-sm-2">
      <p>Ação</p>
    </div>
    <div class="col-sm-3">
    </div>
    <div class="col-sm-2">
      <p>Expira em</p>
    </div>
    <div class="col-sm-2">
      <p>Criado por</p>
    </div>
  </div>

  <% current_user.actions.where(status: 1).each do |action| %>
    <div class="row box-table">
      <div class="col-sm-2">
        <p><span class="lg-status status-waiting">Pendente</span></p>
      </div>
      <div class="col-sm-2">
        <p><%= action.task.try(:title) %></p>
      </div>
      <div class="col-sm-3">
        <p><%= link_to 'Ver detalhes', "#", class: "btn-sm btn-info" %></p>
      </div>
      <div class="col-sm-2">
        <p><%= distance_of_time_in_words(Date.today, action.task.try(:expires_on)) %></p>
      </div>
      <div class="col-sm-3">
        <p>
          <%= render 'panel/shared/avatar', user_name: action.task.user.name %>        
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/_last_wins.html.erb
<div class="last-wins">

  <div class="box">
    <div class="title">
      <h1><i class="fa fa-list"></i> Classificação</h1>
    </div>

    <div class="ranking">
      <div class="row box-table table-header">
        <div class="col-sm-2">
          <p>Posição</p>
        </div>
        <div class="col-sm-8">
          <p>Nome</p>
        </div>
        <div class="col-sm-2">
          <p>Pontos</p>
        </div>
      </div>

      <% Merit::Score.top_scored(limit: 3).each_with_index do |score, index| %>
        <div class="row box-table">
          <div class="col-sm-2 <%= 'user-position' if current_user.id.to_s == score['user_id'] %>">
            <p><%= index + 1 %></p>
          </div>
          <div class="col-sm-8 <%= 'user-position' if current_user.id.to_s == score['user_id'] %>">
            <%= render 'panel/shared/avatar', user_name: User.find(score["user_id"]).name %>
          </div>
          <div class="col-sm-2 <%= 'user-position' if current_user.id.to_s == score['user_id'] %>">
            <p><%= score["sum_points"] %></p>
          </div>
        </div>
      <% end %>

      <div class="row box-table table-header">
        <div class="col-sm-12">
          <p style="text-align:center;"><%= link_to "<i class='fa fa-link'></i> Ver classificação completa".html_safe, ranking_path() %><p>
        </div>
      </div>
    </div>
  </div>

  <div class="box">
    <div class="title">
      <h1><i class="fa fa-star"></i></i> Últimas conquistas</h1>
    </div>

    <div class="wins">
      <ul>
        <% Merit::ActivityLog.where("action_id in (select id from merit_actions where user_id = '#{current_user.id}')").order('created_at desc').limit(5).each do |action| %>
          <li>
            <div class="time">
              <p><i class="fa fa-clock-o"></i> <%= time_ago_in_words(action.created_at) %> atrás</p>
            </div>
            <ul class="win-details">
              <li>
                <% if action.related_change_type == "Merit::Score::Point" %>
                  <div class="circle">
                      <p>
                        <% @merit_points = Merit::Score::Point.find(action.related_change_id) %>
                        <%= @merit_points.num_points %>
                      </p>
                  </div>
                <% else %>
                <div class="trophy">
                  <p><%= image_tag("badges/#{Merit::BadgesSash.find(action.related_change_id).badge.name}.png") %></p>
                </div>
                <% end %>
              </li>
              <li>
                <% if action.related_change_type == "Merit::Score::Point" %>
                  <p class="win-info">
                    <%= Merit::Score.find(@merit_points.score_id).category %>
                  </p>
                <% else %>
                  <p class="win-info info-badge">
                    <%= Merit::BadgesSash.find(action.related_change_id).badge.description %>
                  </p>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="row box-table table-header">
      <div class="col-sm-12">
        <p style="text-align:center;"><%= link_to "<i class='fa fa-link'></i> Ver todas suas conquistas".html_safe, wins_path() %><p>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="dash">
  <div class="row">
    <div class="col-sm-8">
      <%= render 'actions_pending' %>
      <%= render 'actions_waiting' %>
      <%= render 'actions_requiring_approval' %>
    </div>
    <div class="col-sm-4">
      <%= render 'last_wins' %>
    </div>
  </div>
</div>

app/views/dashboard/ranking.html.erb
<div class="dash">
  <div class="row">
    <div class="col-sm-8">
      <div class="box">
        <div class="title">
          <h1><i class="fa fa-list"></i> Classificação</h1>
        </div>

        <div class="ranking">
          <div class="row box-table table-header">
            <div class="col-sm-2">
              <p>Posição</p>
            </div>
            <div class="col-sm-7">
              <p>Nome</p>
            </div>
            <div class="col-sm-3">
              <p>Pontos</p>
            </div>
          </div>

          <% Merit::Score.top_scored(limit: 1000).each_with_index do |score, index| %>
            <div class="row box-table">
              <div class="col-sm-2 <%= 'user-position' if current_user.id.to_s == score['user_id'] %>">
                <p><%= index + 1 %></p>
              </div>
              <div class="col-sm-7 <%= 'user-position' if current_user.id.to_s == score['user_id'] %>">
                <%= render 'panel/shared/avatar', user_name: User.find(score["user_id"]).name %>                
              </div>
              <div class="col-sm-3 <%= 'user-position' if current_user.id.to_s == score['user_id'] %>">
                <p><%= score["sum_points"] %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="box">
        <div class="title">
          <h1><i class="fa fa-bar-chart"></i> Estatísticas</h1>
        </div>

        <div class="task-statistics">
          <ul>
            <li>
              <ul class="task-statistics-details">
                <li>
                  <div class="circle-o">
                    <p><%= User.total_users %></p>
                  </div>
                </li>
                <li>
                  <p class="statistic-info">usuários cadastrados</p>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/dashboard/wins.html.erb
<div class="dash">
  <div class="row">
    <div class="col-sm-8">
      <div class="box">
        <div class="title">
          <h1><i class="fa fa-star"></i></i> Últimas conquistas</h1>
        </div>

        <div class="wins">
          <ul>
            <% Merit::ActivityLog.where("action_id in (select id from merit_actions where user_id = '#{current_user.id}')").order('created_at desc').limit(1000).each do |action| %>
              <li>
                <div class="time">
                  <p><i class="fa fa-clock-o"></i> <%= time_ago_in_words(action.created_at) %> atrás</p>
                </div>
                <ul class="win-details">
                  <li>
                    <% if action.related_change_type == "Merit::Score::Point" %>
                      <div class="circle">
                          <p>
                            <% @merit_points = Merit::Score::Point.find(action.related_change_id) %>
                            <%= @merit_points.num_points %>
                          </p>
                      </div>
                    <% else %>
                      <div class="trophy">
                        <p><%= image_tag("badges/#{Merit::BadgesSash.find(action.related_change_id).badge.name}.png") %></p>
                      </div>
                    <% end %>
                  </li>
                  <li>
                    <% if action.related_change_type == "Merit::Score::Point" %>
                      <p class="win-info">
                        <%= Merit::Score.find(@merit_points.score_id).category %>
                      </p>
                    <% else %>
                      <p class="win-info info-badge">
                        <%= Merit::BadgesSash.find(action.related_change_id).badge.description %>
                      </p>
                    <% end %>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="box">
        <div class="title">
          <h1><i class="fa fa-bar-chart"></i> Estatísticas</h1>
        </div>

        <div class="task-statistics">
          <ul>
            <li>
              <ul class="task-statistics-details">
                <li>
                  <div class="circle-o">
                    <p><%= current_user.total_wins %></p>
                  </div>
                </li>
                <li>
                  <p class="statistic-info">conquistas</p>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>