config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "site#index"

  match '/dashboard' => 'dashboard#index', :via => [:get]
  match '/ranking' => 'dashboard#ranking', :via => [:get]
  match '/wins' => 'dashboard#wins', :via => [:get]

  resources :tasks do
    post :share, :on => :member
  end

  resources :posts do
    post :like, :on => :member
    post :unlike, :on => :member
  end

  resources :comments, only: [:index, :create]
  
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  match '/actions/:task_id/participate' => 'actions#participate', :via => [:post]
  match '/actions/:action_id/confirmate' => 'actions#confirmate', :via => [:post]
  match '/actions/:action_id/finalize' => 'actions#finalize', :via => [:post]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy

  attr_accessible :text, :task_id, :user_id

  def liked?(user_id)
    self.likes.where(user_id: user_id).blank?
  end

  def post_is_own?(user_id)
    self.user.id == user_id
  end

  def self.total_posts
    Post.count
  end

end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  before_action :authenticate_user!

  before_action :set_menu_context, if: ->() { user_signed_in? }

  def set_menu_context
    @menu_context = actual_menu_context
  end

  def index
    @post = current_user.posts.new
  end

  def create
    create!{ posts_path }
  end

  def like
    @post = load_model
    current_user.likes.create!(post_id: @post.id)
    render :index
  end

  def unlike
    @like = load_like
    @like.destroy
    render :index
  end

  protected

  def begin_of_association_chain
    current_user
  end

  def load_model
    @post = Post.find(params[:id])
  end

  def load_like
    @like = current_user.likes.where(post_id: params[:id]).last
  end

  private

  def actual_menu_context
    :timeline
  end

end

app/views/posts/index.html.erb
<div class="dash">
  <div class="row">
    <div class="col-sm-8">
      <% first = true %>
      <% Post.all.order(created_at: :desc).limit(10).each do |post| %>
        <div class="box">
          <% if first %>
            <div class="title">
              <h1><i class="fa fa-comments"></i> Linha do Tempo</h1>
            </div>
            <% first = false %>
          <% end %>

          <div class="row box-table">
            <div class="col-sm-9 table-header">
              <p>
                <%= render 'panel/shared/avatar', user_name: post.user.name %>
                 <span style="margin-left: 5px;">compartilhou a ação </span>
                <strong>
                  <%= link_to "#{post.task.title}", task_path(post.task) %>
                </strong>
              </p>
            </div>
            <div class="col-sm-3 time time-right">
              <p>
                <i class="fa fa-clock-o"></i>
                <%= time_ago_in_words(post.created_at) %> atrás
              </p>
            </div>
          </div>
          <% unless post.text.blank? %>
            <div class="row box-table">
              <div class="col-sm-12">
                <p><%= post.text %><p>
              </div>
            </div>
          <% end %>
          <div class="row box-table">
            <div class="col-sm-12">
              <div class="box-task">
                <p><%= post.task.description %><p>
                <div class="box-info">
                  <p>
                    <i class="fa fa-map-marker"></i>
                    Esta ação está localizada em <%= post.task.city %>, <%= post.task.province %>
                    <%= link_to 'Ver detalhes', task_path(post.task), class: "btn-sm btn-info pull-right" %>
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div class="row box-table">
            <div class="box-actions">
              <div class="col-sm-10">
                <% unless post.liked?(current_user.id) %>
                  <%= link_to '<i class="fa fa-heart ico-likes"></i>'.html_safe, unlike_post_path(post), class: "btn-unlike", :method => :post, :remote => true %>
                <% else %>
                  <%= link_to '<i class="fa fa-heart-o ico-likes"></i>'.html_safe, like_post_path(post), class: "btn-like", :method => :post, :remote => true %>
                <% end %>

                <% unless post.likes.blank? %>
                  <span class="n-likes"><%= post.likes.count %></span>
                <% end %>

                <% unless post.comments.blank? %>
                  <a class="btn-comments" href="#">
                    <i class="fa fa-comment ico-comments"></i>
                    <span class="n-comments"><%= post.comments.count %></span>
                  </a>
                <% else %>
                  <i class="fa fa-comment-o ico-comments"></i><span class="n-comments"></span>
                <% end %>

                <i class="fa fa-share-square-o ico-shares"></i></i>
                <% if post.task.total_share > 0 %>
                  <span class="n-shares"><%= post.task.total_share %></span>
                <% end %>
              </div>
              <div class="col-sm-2">
                <% if post.post_is_own?(current_user.id) %>
                  <a class="btn-remove-post pull-right" href="#" data-post-id="<%= post.id %>">
                    <i class="fa fa-times ico-remove"></i>
                  </a>
                <% end %>
              </div>
            </div>
          </div>

          <div class="row show-comments">
            <div class="col-sm-12">
              <% post.comments.limit(2).order("created_at DESC").each do |comment| %>
                <div class="comments-container">
                  <div class="row box-comments">
                    <div class="">
                        <div class="col-sm-9 comments-header box-table">
                          <%= render 'panel/shared/avatar', user_name: comment.user.name %>
                        </div>
                        <div class="col-sm-3 time comments-header">
                          <p>
                            <i class="fa fa-clock-o"></i>
                            <%= time_ago_in_words(comment.created_at) %> atrás
                          </p>
                        </div>
                    </div>
                  </div>

                  <div class="row box-comments">
                    <div class="">
                      <div class="col-sm-11 comments-body">
                        <%= comment.text %>
                      </div>
                      <div class="col-sm-1 comments-sentiment">
                        <% if comment.good? %>
                          <i class="fa fa-smile-o" style="color: green;" title="Comentário positivo"></i>
                        <% else %>
                          <i class="fa fa-frown-o" style="color: blue" title="Comentário negativo"></i>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="row box-table">
            <div class="box-actions">
              <div class="col-sm-12">

                <%= simple_form_for(post.comments.build, url: comments_path,
                  format: :json, remote: true, method: :post) do |f| %>

                  <%= f.input :parent_id, as: :hidden %>

                  <input name="comment[post_id]" type="hidden" value="<%= post.id %>">
                  <input name="comment[user_id]" type="hidden" value="<%= current_user.id %>">
                  <input type="text" name="comment[text]" placeholder="Deixe o seu comentário (Aperte Enter para enviar)"
                    class="in-comment"></input>
                <% end %>


              </div>
            </div>
          </div>

        </div>
      <% end %>
    </div>
    <div class="col-sm-4">
      <div class="box">
        <div class="title">
          <h1><i class="fa fa-bar-chart"></i> Estatísticas</h1>
        </div>

        <div class="task-statistics">
          <ul>
            <li>
              <ul class="task-statistics-details">
                <li>
                  <div class="circle-o">
                    <p><%= Post.total_posts %></p>
                  </div>
                </li>
                <li>
                  <p class="statistic-info">publicações</p>
                </li>
              </ul>
            </li>
            <li>
              <ul class="task-statistics-details">
                <li>
                  <div class="circle-o">
                    <p><%= current_user.posts.count %></p>
                  </div>
                </li>
                <li>
                  <p class="statistic-info">publicações feitas por você</p>
                </li>
              </ul>
            </li>
            <li>
              <ul class="task-statistics-details">
                <li>
                  <div class="circle-o">
                    <p><%= current_user.likes.count %></p>
                  </div>
                </li>
                <li>
                  <p class="statistic-info">curtidas feitas por você</p>
                </li>
              </ul>
            </li>
            <li>
              <ul class="task-statistics-details">
                <li>
                  <div class="circle-o">
                    <p><%= current_user.comments.count %></p>
                  </div>
                </li>
                <li>
                  <p class="statistic-info">comentários feitos por você</p>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</div>